version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "(%(asctime)s) [%(levelname)s] %(message)s"
  fullline:
    format: "(%(asctime)s) [%(levelname)s] {%(filename)s#%(lineno)d} %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    maxBytes: 1048576
    filename: var/log/dummy.log
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, file_handler]
